### ISSUE TITLE
Suggestion: cover fselect, a CLI tool for finding files with SQL syntax

### ISSUE THREAD

**Issue by jhspetersson** [delucks/cli.fan#2]
URL: https://github.com/jhspetersson/fselect

And I am the author. Any questions and feedback are highly appreciated!

**Comment by jhspetersson** [comment]
Thank you so much for the review! I wish I was able to write in such a clear and understandable way :)

You even spotted one weakness that is mentioned below the line:

    Note that results of these functions cannot be the inputs to other functions:

I supposed it to be a bug and therefore fixed it in a master. Soon to be included into the next release. If it's possible could you please update the original post or probably I could make a PR :)

Anyway, thanks again for your attention!

**Comment by delucks** [comment]
Hey @jhspetersson sorry it took me so long to get back to you! I added an update to cover what you noted in 55223c148021646fd114803c2b53d27b2c92eeb9. I appreciate you giving this issue an update and the fix to that behavior
