### ISSUE TITLE
Website is unreachable

### ISSUE THREAD

**Issue by thezeroalpha** [delucks/cli.fan#8]
Hi, I was following your posts on cli.fan but the site is now unreachable for me, the connection times out. I'm not sure if you were aware, so I figured I'd let you know.

**Comment by delucks** [comment]
Thanks for the report @thezeroalpha! I have had been going through hard times recently and I stopped maintaining the hosting. It's back up now and hopefully more robust.

**Comment by thezeroalpha** [comment]
@delucks Of course, that's completely understandable. I hope things are going better for you now.
